name: Build with CMake/LLVM

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "docker/**"
  push:
    branches:
      - "master"
    paths-ignore:
      - "docker/**"
    
env: 
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  COMMIT_ID: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/emilycsh/brother-laser-pappl_build:sha-1f10156bb0bd61eff42d49d7bd8c2b9ae1d71d8a
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Setup CMake Environment
        run: |
          cmake -G Ninja -Bbuild -DLINK_STATIC_PAPPL=ON -DLINK_EXPLICIT_LIBC++=ON .
      - name : CMake Build
        run: |
          cmake --build build -- -v
      - uses: actions/upload-artifact@v7
        with:
          name: brother-laser-pappl_${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}
          path: build/brother-laser-pappl
